version: 1.0

jobs: 
  nombreJobPrueba:
    docker: 
      - image: cimg/node:14.13.0
    steps: 
      - checkout
      - run: node --version
        

workflows: 
  flujoDeTrabajoEjemplo: 
    jobs:
      - nombreJobPrueba
