version 1.0

workflows: 
  flujoDeTrabajoEjemplo: 
    jobs:
      - nombreJobPrueba

jobs: 
  nombreJobPrueba:
    executor: 
      docker: 
        - image: cimg/node:7.0
    steps: 
      - checkout
      - run: node --version
        

